/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aurora: typeof import('./src/components/public/inspiraUI/Aurora.vue')['default']
    AuthBtn: typeof import('./src/components/public/AuthBtn/index.vue')['default']
    AvatarUpload: typeof import('./src/components/admin/avatarUpload.vue')['default']
    BasePagination: typeof import('./src/components/public/basePagination.vue')['default']
    BlurReveal: typeof import('./src/components/public/inspiraUI/BlurReveal.vue')['default']
    Category: typeof import('./src/components/admin/category.vue')['default']
    Dropdown: typeof import('./src/components/public/UiverseUi/dropdown.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    FileUpload: typeof import('./src/components/admin/fileUpload.vue')['default']
    GradientButton: typeof import('./src/components/public/inspiraUI/GradientButton.vue')['default']
    IconDialog: typeof import('./src/components/public/IconDialog/index.vue')['default']
    IconifyIcon: typeof import('./src/components/public/IconifyIcon/index.vue')['default']
    Image: typeof import('./src/components/admin/image.vue')['default']
    Marquee: typeof import('./src/components/public/inspiraUI/Marquee.vue')['default']
    MorphingTabs: typeof import('./src/components/public/inspiraUI/MorphingTabs.vue')['default']
    OpcityCard: typeof import('./src/components/public/opcityCard.vue')['default']
    RadiantText: typeof import('./src/components/public/inspiraUI/RadiantText.vue')['default']
    ReviewCard: typeof import('./src/components/public/inspiraUI/ReviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/public/Switch/theme.vue')['default']
    Transfer: typeof import('./src/components/admin/transfer.vue')['default']
    WangEdit: typeof import('./src/components/public/wangEdit.vue')['default']
  }
}
